version: "3"

services:
  pawnscli:
    container_name: pawnscli
    image: arville27/pawnscli
    build: .
    environment:
      - "EMAIL=${EMAIL}"
      - "PASSWORD=${PASSWORD}"
      - "DEVICE_NAME=${DEVICE_NAME}"
    restart: always
